### Create a shortener url
POST https://your-url.lambda-url.us-east-1.on.aws/ HTTP/1.1
Content-Type: application/json

{
  "originalUrl": "https://github.com/maycon8609/url-shortener",
  "expirationTime": "1735167600000"
}

# "expirationTime": "1735167600000" === 2024-12-25T20:00:00